---
title: React Query
description: Learn how to use CallApi with React Query
---

## Basic Usage

By default, CallApi returns a result object containing both success and error data. However, React Query works differently - it expects either a resolved promise with data or a rejected promise with an error. To bridge this gap, we need to configure CallApi properly:

```ts title="todo.tsx"
import { callApi } from "@zayne-labs/callapi";
import { useQuery } from "@tanstack/react-query";

type Todo = {
	id: number;
	title: string;
	completed: boolean;
};

const { data, isPending, isError, error } = useQuery({
	queryKey: ["todos"],
	queryFn: () => {
		return callApi<Todo[], unknown, "onlySuccessWithException">("https://my-api.com/api/v1/todos", {
			throwOnError: true,
			resultMode: "onlySuccessWithException",
		});
	},
});
```

The two key options we're using here are:

- [throwOnError](../extra-options.mdx): true - This setting makes CallApi throw errors instead of returning them in the result object
- [resultMode](../extra-options.mdx): "onlySuccessWithException" - This setting makes CallApi return just the data property with its exact type (i.e. `Todo[]` instead of `Todo[] | null`), since that's mostly all we care about in this scenario.

However, due to current TypeScript limitations with partial generic inference (see [TypeScript#26242](https://github.com/microsoft/TypeScript/issues/26242)), we also had to manually specify `"onlySuccessWithException"` as the third generic argument to prevent type errors.

To avoid this, you can either:

1. Use validation libraries like zod to [validate the response data and infer the type](/docs/v1/getting-started#response-validation)

```ts title="todo.tsx"
import { callApi } from "@zayne-labs/callapi";
import { useQuery } from "@tanstack/react-query";
import { z } from "zod";

const todoSchema = z.object({
	id: z.number(),
	title: z.string(),
	completed: z.boolean(),
});

const { data, isPending, isError, error } = useQuery({
	queryKey: ["todos"],
	queryFn: () => {
		return callApi("https://my-api.com/api/v1/todos", {
			schemas: {
				data: todoSchema,
			},
			throwOnError: true,
			resultMode: "onlySuccessWithException",
		});
	},
});
```

2. Pass `false` as the second generic argument to signal that errors will be thrown

```ts title="todo.tsx"
import { callApi } from "@zayne-labs/callapi";
import { useQuery } from "@tanstack/react-query";

type Todo = {
	id: number;
	title: string;
	completed: boolean;
};

const { data, isPending, isError, error } = useQuery({
	queryKey: ["todos"],
	queryFn: () => {
		return callApi<Todo[], false>("https://my-api.com/api/v1/todos", {
			throwOnError: true,
			resultMode: "onlySuccessWithException",
		});
	},
});
```
